### PR TITLE
Adding strict type declaration

### PR DESCRIPTION
**Pull request by burzum**

### CODE REVIEW

**Comment by frankdejonge** [comment]
Hi @burzum, the branch was already merged with master, which is now a couple commits ahead where some of these changes have already been done. Could you check master?

**Comment by burzum** [comment]
@frankdejonge yes, I'll see when I can find time for that today.

**Comment by burzum** [comment]
@frankdejonge where did the specs go? You deleted them by accident?

**Comment by frankdejonge** [comment]
@burzum nope, I don't want to write specs anymore. I used normal PHPUnit tests for this version.

**Comment by burzum** [comment]
@frankdejonge I appreciate that decision. Have you already written tests or is this something that can be done in a PR?

**Comment by frankdejonge** [comment]
The tests are already there, next to the code (same directory) 🙂

**Comment by burzum** [comment]
Oh... 🙂 I didn't realize that and was looking for a "tests" folder... My fault! I'm not putting them in the same folder for that reason in my projects.

**Pull request closed without merging**
