### PR TITLE
Version 3: PSR-14

### PR DESCRIPTION
**Pull request by frankdejonge**
This PR makes league/event compatible with PSR-14. It adopts the terminology from the PSR to ensure people have a good understanding of what the components are and what they should be used for.

Notable changes:

- All PSR-14 terminology is used
- Emitter is now EventDispatcher
- BufferedEmitter is removed
- String-based event dispatching is removed (named events are still supported).
- Generator is now EventGenerator
- Listener::handle is now Listener::__invoke to be compatible with PSR-14

### CODE REVIEW

**Comment by sa-tasche** [comment]
Accepted: PSR14 Event Dispatcher:
https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-14-event-dispatcher.md

**Comment by burzum** [comment]
Is the project dead? This PR is open for more than a year now.

**Comment by burzum** [comment]
I've either missed a few files or it's because of the merge, I'm going to add the strict type declaration where it is missing.

Everything else seems to be OK, but I'll check it tomorrow again.

**Comment by Circlepuller** [comment]
Thanks for doing this! :+1:

**Pull request merged**
